theme: "minima"
url: "https://glondono.github.io/lantz"
title: "Lantz Mills"
header_pages:
  - about.md
  - history.md
  - restoration.md
  - importance.md
  - photos.md
  - location.md
  - contact.md
